/* 
 * FaaS API Gateway
 *
 * FaaS API documentation
 *
 * OpenAPI spec version: 0.6.5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type CreateFunctionRequest struct {

	// Name of deployed function
	Service string `json:"service,omitempty"`

	// Docker swarm network, usually func_functions
	Network string `json:"network,omitempty"`

	// Docker image in accessible registry
	Image string `json:"image,omitempty"`

	// Process for watchdog to fork
	EnvProcess string `json:"envProcess,omitempty"`

	// Overrides to environmental variables
	EnvVars []string `json:"envVars,omitempty"`

	// Private registry base64-encoded basic auth (as present in ~/.docker/config.json)
	RegistryAuth string `json:"registryAuth,omitempty"`
}
