/* 
 * FaaS API Gateway
 *
 * FaaS API documentation
 *
 * OpenAPI spec version: 0.6.5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type DeleteFunctionRequest struct {

	// Name of deployed function
	FunctionName string `json:"functionName,omitempty"`
}
